name: Build & Deploy

on:
  push:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ['18.18.2']

    steps:
      - uses: actions/checkout@v3
      - name: Build
        uses: TartanLlama/actions-eleventy@master
        with:
          install_dependencies: true
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: _site 
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
